[package]
name = "rdiff-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.23.14"
rayon = "1.5.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "sim_bench"
harness = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
